springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
#spring:
#  mvc:
#    view:
#      suffix: .html
  thymeleaf:
#    prefix: classpath:/templates/
    cache: false
  banner:
    location: classpath:/banner.txt
server:
  port: 8080


